#!/usr/bin/env sh
#
# 00_Install makes sure neovim is installed before doing the rcup call.
#

if command -v nvim > /dev/null; then
  echo "neovim is already installed"
else
  sh ../../pre-setup.sh install neovim
fi
