#!/usr/bin/env sh

if [ ! -f installer.sh ]; then
  curl -L https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh > installer.sh
fi

mkdir -p ~/.cache/dein

sh ./installer.sh ~/.cache/dein

nvim +"call dein#check_install()" +"call dein#install()" +qall
